version: '3.8'

services:
  vpc-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_AUTH_URL=${NEXT_PUBLIC_AUTH_URL}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: vpc-app
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
